riders/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('riders.views',
    url(r'^$', 'index'),
    url(r'^login', 'login', name='auth_login'),
    url(r'^logout', 'logout', name='auth_logout'),
    url(r'^register', 'register', name='rider_registration'),
    url(r'^(?P<id>(\d+))/$', 'profile'),
    url(r'^(?P<id>(\d+))/(?P<slug>(.+))/$', 'profile'),
)

urlpatterns += patterns('',
    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset', {
        'post_reset_redirect' : '/riders/password/reset/done/',
        'template_name': 'riders/resetpassword.html'
    }, name='reset_password'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', {
        'template_name': 'riders/resetpassword_done.html'
    }),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {
        'post_reset_redirect' : '/riders/password/done/',
        'template_name': 'riders/resetpassword_confirm.html'
    }),
    url(r'^password/done/$', 'django.contrib.auth.views.password_reset_complete', {
        'template_name': 'riders/resetpassword_complete.html'
    }),
)

rides/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('rides.views',
    url(r'^$', 'index'),
    url(r'^(?P<slug>(.+))/$', 'details'),
)

riders/models.py
from django.db import models
from django.contrib.auth.models import User

class RiderProfile(models.Model):
    # Link to main user record
    user = models.OneToOneField(User, primary_key = True)

    # Extended User Information
    company = models.CharField(max_length=200, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    twitter = models.CharField(max_length=200, null=True, blank=True)

    biography = models.TextField(blank=True)

    def __unicode__(self):
        return self.user.username

    class Meta:
        db_table    = "riders_profiles"
        app_label   = 'riders'

riders/forms.py
from django.contrib.auth.models import User
from django import forms

class RiderRegistration(forms.Form):
    firstname = forms.CharField(max_length=60, label="First name", widget=forms.TextInput(attrs={
        "placeholder": "First name",
        "data-val": "true",
        "data-val-required": "You can't leave this empty"
    }))
    lastname = forms.CharField(max_length=60, label="Last name", widget=forms.TextInput(attrs={
        "placeholder": "Last name",
        "data-val": "true",
        "data-val-required": "You can't leave this empty"
    }))
    email = forms.EmailField(label="E-mail", widget=forms.TextInput(attrs={
        "placeholder": "Email address",
        "data-val": "true",
        "data-val-required": "You can't leave this empty",
        "data-val-regex": "Please enter a valid email address",
        "data-val-regex-pattern": "^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$"
    }))
    company = forms.CharField(label="Company", required=False, widget=forms.TextInput(attrs={
        "placeholder": "Company"
    }))
    website = forms.CharField(label="Website", required=False, widget=forms.TextInput(attrs={
        "placeholder": "Website"
    }))
    twitter = forms.CharField(label="Twitter", required=False, widget=forms.TextInput(attrs={
        "placeholder": "Twitter"
    }))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={
        "placeholder": "Password",
        "data-val": "true",
        "data-val-required": "You can't leave this empty"
    }))
    password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={
        "placeholder": "Confirm password",
        "data-val": "true",
        "data-val-required": "You can't leave this empty",
        "data-val-equalto": "Passwords must match",
        "data-val-equalto-other": "password1"
    }))

    def clean_email(self):
        # Check that the email is not already in use
        user = User.objects.filter(username__iexact = self.cleaned_data['email'])
        if user.exists():
            raise forms.ValidationError("A user with that email already exists.")
        else:
            return self.cleaned_data['email']

    def clean(self):
        # Verifiy that the values entered into the two password fields match.
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("The two password fields didn't match.")
        return self.cleaned_data

class ChangePassword(forms.Form):
    oldpassword = forms.CharField(label="Current Password", widget=forms.PasswordInput(attrs={
        "placeholder": "Current password",
        "data-val": "true",
        "data-val-required": "You can't leave this empty"
    }))
    newpassword1 = forms.CharField(label="New Password", widget=forms.PasswordInput(attrs={
        "placeholder": "New password",
        "data-val": "true",
        "data-val-required": "You can't leave this empty"
    }))
    newpassword2 = forms.CharField(label="Confirm new password", widget=forms.PasswordInput(attrs={
        "placeholder": "Confirm new password",
        "data-val": "true",
        "data-val-required": "You can't leave this empty",
        "data-val-equalto": "Passwords must match",
        "data-val-equalto-other": "newpassword1"
    }))

    def clean(self):
        # Verifiy that the values entered into the two password fields match.
        if 'newpassword1' in self.cleaned_data and 'newpassword2' in self.cleaned_data:
            if self.cleaned_data['newpassword1'] != self.cleaned_data['newpassword2']:
                raise forms.ValidationError("The two password fields didn't match.")
        return self.cleaned_data

class RiderDetails(forms.Form):
    firstname = forms.CharField(max_length=60, label="First name:", widget=forms.TextInput(attrs={
        "placeholder": "First name",
        "data-val": "true",
        "data-val-required": "You can't leave this empty",
        "data-tooltip": "We like people at Knodium to be on name terms"
    }))
    lastname = forms.CharField(max_length=60, label="Last name:", widget=forms.TextInput(attrs={
        "placeholder": "Last name",
        "data-val": "true",
        "data-val-required": "You can't leave this empty"
    }))
    newpassword1 = forms.CharField(label="New Password", widget=forms.PasswordInput(attrs={
        "placeholder": "New password",
        "data-val": "true",
        "data-val-required": "You can't leave this empty"
    }))
    newpassword2 = forms.CharField(label="Confirm new password", widget=forms.PasswordInput(attrs={
        "placeholder": "Confirm new password",
        "data-val": "true",
        "data-val-required": "You can't leave this empty",
        "data-val-equalto": "Passwords must match",
        "data-val-equalto-other": "newpassword1"
    }))

    def clean(self):
        # Verifiy that the values entered into the two password fields match.
        if 'newpassword1' in self.cleaned_data and 'newpassword2' in self.cleaned_data:
            if self.cleaned_data['newpassword1'] != self.cleaned_data['newpassword2']:
                raise forms.ValidationError("The two password fields didn't match.")
        return self.cleaned_data

riders/views.py
from django.shortcuts import render, redirect
from django.template.defaultfilters import slugify
from django.http import Http404
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from riders.forms import RiderRegistration
from riders.models import RiderProfile


def index(request):
    #return render(request, 'riders/index.html')
    raise Http404


def login(request):
    if request.user.is_authenticated():
        return redirect('riders.views.index')
    else:
        if request.method == 'GET':
            if request.user.is_authenticated():
                return redirect('riders.views.index')

            return render(request, 'riders/login.html', {'next': request.GET.get('next', '')})

        elif request.method == 'POST':
            username = request.POST['email']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    auth_login(request, user)

                    # See if the user needs redirecting
                    next_page = request.POST.get('next', None)
                    if next_page:
                        return redirect(next_page)
                    else:
                        return redirect(settings.LOGIN_REDIRECT_URL)
                else:
                    return render(request, 'riders/login.html', {'errors': 'Account disabled'})
            else:
                return render(request, 'riders/login.html', {'errors': 'Incorrect username or password'})


def logout(request):
    auth_logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


def register(request):
    if request.user.is_authenticated():
        return redirect("riders.views.index")
    else:
        if request.method == "GET":
            # Initialise the signup form
            form = RiderRegistration(auto_id=True)
            return render(request, 'riders/register.html', {"form": form, 'next': request.GET.get('next', '')})

        elif request.method == "POST":
            form = RiderRegistration(request.POST)
            if form.is_valid():
                # Get the form data
                email    = form.clean_email()
                password = form.cleaned_data["password1"]
                # Create the new user
                new_user = User.objects.create_user(email, email, password)
                new_user.first_name = form.cleaned_data["firstname"]
                new_user.last_name = form.cleaned_data["lastname"]
                new_user.save()

                # Create a blank user profile
                profile = RiderProfile.objects.create(user=new_user)
                profile.company = form.cleaned_data["company"]
                profile.website = form.cleaned_data["website"]
                profile.twitter = form.cleaned_data["twitter"]
                profile.save()

                # Log the user in
                user = authenticate(username=email, password=password)
                auth_login(request, user)

                # See if the user needs redirecting
                next_page = request.POST.get('next', None)
                if next_page:
                    return redirect(next_page)
                else:
                    return redirect('/')
            else:
                # Errors in the form so return with the errors
                return render(request, 'riders/register.html', {"form": form})


def profile(request, id, slug = None):
    # Try and get the user from the id
    try:
        user = User.objects.get(id = id)
    except User.DoesNotExist:
        raise Http404

    # Get the user slug
    user_slug = slugify(user.get_full_name())

    # Check if the name is in the url, redirect if not
    if not slug:
        return redirect("/riders/%s/%s" % (user.id, user_slug))

    # Check if the title is the right one, throw error if not to stop bad linking
    if slug != user_slug:
        raise Http404

    return render(request, "riders/profile.html", {"profile": user})

templates/riders/index.html
{% extends "shared/_base.html" %}

{% block content %}
hello!
{% endblock content %}

templates/riders/login.html
{% extends "shared/_base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="content">
        <section>
            <header>
                <h1>Login</h1>
            </header>
            <br/>
            <form id="loginform" method='post' novalidate="novalidate">
                {% csrf_token %}
                <div class="row centerText">
                    <input type="text" name="email" value="" id="Email" placeholder="email address"
                           data-val="true"
                           data-val-required="Please enter your email address"
                           data-val-regex="Email Format is wrong"
                           data-val-regex-pattern="^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$" >
                </div>
                <div class="row centerText">
                    <input type="password" name="password" value="" id="Password" placeholder="password"
                           data-val="true"
                           data-val-required="Please enter your password" >
                </div>
                <div class="row">
                  <p class="centerText">
                    <input type="submit" value="Login" class="btn" />
                  </p>
                  <p class="centerText">
                      Don't have an account yet? <a href="{% url "rider_registration" %}{% if next %}?next={{ next }}{% endif %}">Create one!</a>
                      <br/>
                      <a href="{% url "reset_password" %}">Forgotten your password?</a>
                  </p>
                </div>
                <input type="hidden" name="next" value="{{ next }}"/>
            </form>
        </section>
    </div>
{% endblock %}

templates/riders/profile.html
{% extends "shared/_base.html" %}

{% load gravatar %}

{% block title %}{{ profile.get_full_name }} - Techbikers{% endblock %}

{% block content %}
<section>
    {% gravatar profile.email 130 %}

    <h2>{{ profile.get_full_name }}</h2>
</section>
{% endblock content %}

templates/riders/register.html
{% extends "shared/_base.html" %}

{% block content %}
<div class="content">
  <section>
    <header>
      <h1>Register for Techbikers 2013</h1>
    </header>

    <ol class="steps">
      <li class="active">
        <span>1</span>
        <span>Join Techbikers</span>
      </li>

      <li>
        <span>2</span>
        <span>Pay the ride fee</span>
      </li>

      <li>
        <span>3</span>
        <span>Registration Complete!</span>
      </li>
    </ol>

    <form method="post">
    {% csrf_token %}

      {{ form.errors }}

      <div class="row">
        <div class="span2 offset1">
          {{ form.firstname }}
          <span class="field-validation-valid" data-valmsg-for="firstname" data-valmsg-replace="true"></span>

          {{ form.lastname }}
          <span class="field-validation-valid" data-valmsg-for="lastname" data-valmsg-replace="true"></span>

          {{ form.email }}
          <span class="field-validation-valid" data-valmsg-for="email" data-valmsg-replace="true"></span>

          {{ form.company }}
        </div>

        <div class="span2">
          {{ form.website }}
          {{ form.twitter }}
          {{ form.password1 }}
          <span class="field-validation-valid" data-valmsg-for="password1" data-valmsg-replace="true"></span>
          {{ form.password2 }}
          <span class="field-validation-valid" data-valmsg-for="password2" data-valmsg-replace="true"></span>

        </div>
      </div>
    </div>
    <input type="hidden" name="next" value="{{ next }}"/>
    <p class="centerText">
      <input type="submit" value="Sign Up" class="btn" />
    </p>
    <p class="centerText">
      <a href="{% url "auth_login" %}{% if next %}?next={{ next }}{% endif %}">Already have an account?</a>
    </p>
  </form>
</div>
{% endblock content %}

templates/riders/resetpassword.html
{% extends "shared/_base.html" %}

{% block content %}
<div class="content">
    <section>
        <header>
            <h1>Reset your password</h1>
        </header>

        <p class="centerText">
            Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one.
        </p>

        {% if form.errors %}
            <span  class="centerText field-validation-error">
                {% for error in form.email.errors %}
                    {{ error }}
                {% endfor %}
            </span>
        {% endif %}

        <form action="" method="post">
            {% csrf_token %}

            <div class="centerText">
                <input id="id_email" type="text" name="email" maxlength="75"
                       data-val="true"
                       data-val-required="You can't leave this empty"
                       data-val-regex="Please enter a valid email address"
                       data-val-regex-pattern="^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$"
                       placeholder="Email address"><br/>
                <span class="field-validation-valid" data-valmsg-for="email" data-valmsg-replace="true"></span>
            </div>

            <p class="centerText">
                <input type="submit" class="btn btn-primary" value="Reset my password"/>
            </p>
        </form>
    </section>
</div>
{% endblock %}

templates/riders/resetpassword_complete.html
{% extends "shared/_base.html" %}

{% block content %}
<div class="content">
    <section>
        <header>
            <h1>Password reset successfully!</h1>
        </header>

        <p>
            Your password has been set. You may go ahead and log in now.
        </p>

        <p class="centerText">
            <a class="btn" href="{% url "auth_login" %}">Log in</a>
        </p>
    </section>
</div>
{% endblock %}

templates/riders/resetpassword_confirm.html
{% extends "shared/_base.html" %}

{% block content %}
<div class="content">
    <section>
        {% if validlink %}
            <header>
                <h1>Create a new password</h1>
            </header>

            {% if form.errors %}
                <div class="errors">
                    {{ form.errors }}
                </div>
            {% endif %}

            <p>
                Please enter your new password twice so we can verify you typed it in correctly.
            </p>

            <form action="" method="post">
                {% csrf_token %}

                <div class="centerText">
                        <input type="password" name="new_password1" id="id_new_password1" placeholder="New password"
                               data-val="true" data-val-required="You can't leave this empty"><br/>
                    <span class="field-validation-valid" data-valmsg-for="new_password1" data-valmsg-replace="true"></span>
                </div>

                <div class="centerText">
                    <input type="password" name="new_password2" id="id_new_password2"
                               placeholder="Confirm new password" data-val="true"
                               data-val-required="You can't leave this empty"
                               data-val-equalto="Passwords must match"
                               data-val-equalto-other="new_password1"><br/>
                    <span class="field-validation-valid" data-valmsg-for="new_password2" data-valmsg-replace="true"></span>
                </div>

                <p class="centerText">
                    <input type="submit" class="btn btn-primary" value="Reset my password"/>
                </p>
            </form>

        {% else %}

            <header>
                <h1>Password reset unsuccessful</h1>
            </header>

            <p>
                The password reset link was invalid, possibly because it has already been used. Please request a new password reset.
            </p>

        {% endif %}
    </section>
</div>
{% endblock %}

templates/riders/resetpassword_done.html
{% extends "shared/_base.html" %}

{% block content %}
<div class="content">
   <section>
       <header>
           <h1>Password Reset - Email Sent!</h1>
       </header>

       <p>
           We've e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly.
       </p>
   </section>
</div>
{% endblock %}